/**
 * Created by Darren on 11/15/2017.
 *Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

 */
public class No2 {
    public static void main(String[] args) {
        int a = 1;
        int b = 2;
        int counter = 0;
        while(a<4000000){
            if((a&1)==0){
                counter+=a;
            }
            b=a+b;
            a=b-a;
        }
        System.out.println(counter);
        System.out.println("Nice!");
    }
}
